development:
  host: localhost
  database: biblio_bridge_development

test:
  host: localhost
  database: biblio_bridge_test

# set these environment variables on your prod server
production:
  uri: <%=ENV['MONGOLAB_URI']%>

