development:
  host: localhost
  database: heorot_development

test:
  host: localhost
  database: heorot_test

# set these environment variables on your prod server
production:
  uri: <%=ENV['MONGOLAB_URI']%>

